name: reviewdog

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
            go_verrsion: "1.20"
            golangci_lint_flag: "--config=login/.golangci.yml"
            github_token: ${{ github.token }}
            level: warning
            filter_mode: nofilter
            workdir: "login/"
            reporter: github-pr-review
